### ISSUE TITLE
Dependencies with dev-master

### ISSUE THREAD

**Issue by mbittner** [ulff/BehatRestApiExtension#15]
Hi there,

When looking at the requirements, I see you require dev-master of some of the components you're using.
Anyway to specify minimum version instead? I don't like using dev-master of components. I already use this for exemple:

        "behat/mink-extension": "^2.2",
        "behat/mink-goutte-driver": "^1.2",
        "behat/mink-selenium2-driver": "^1.3",

along with behat 3.3.1

Thanks

**Comment by ulff** [comment]
@mbittner closed, versions sticked to the stable ones, except codifico/parameter-bag-extension, which doesn't have stable version.
